name: deploy to aws s3
# main 브랜치에 push 될 때 현재 스크립트 실행 트리거 발동
on:
  push:
    branches:
      - temp
jobs:
# workflow는 하나 이상의 작업(job)으로 구성. 여기서는 하나의 작업만을 정의
  build-and-deploy:
    runs-on: ubuntu-latest # 우분투 최신 판에서 작업(빌드, 배포 작업 어디서 할건지 지정)
    steps:
    # actions는 깃헙에서 제공되는 공식 워크플로이다.
    # checkout은 현재 repo의 main 브랜치 소스코드를 copy
      - name: source code checkout
        uses: actions/checkout@v2
        # node js 세팅
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: pnpm install
        working-directory: .
        # run은 직접 사용하고자 하는 명령어이다.
        run: npm install
      - name: npm build
        working-directory: .
        run: npm run build
      - name: setup aws cli
      # aws 관련한 aws actions가 제공된다. 지금 이게 configure 세팅하는 거임
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET}}
          aws-region: "ap-northeast-2"
        # 버킷에 소스코드 붓기
      - name: clear s3 bucket
        # 기존 s3 버킷을 비워주기
        run: aws s3 rm s3://www.dev.si-d.site/ --recursive
        
        # S3에 넣기
      - name: deploy to s3
        run: aws s3 cp ./dist s3://www.dev.si-d.site/ --recursive